### ISSUE TITLE
after arch_rebuild, why is there no Arch Migrator here

### ISSUE THREAD

**Issue by yangxingyu588** [conda-forge/r-rjags-feedstock#20]
### Additional comment:

l've addedr-rjags to the https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/56e9223877f1fd0096441d00e91393602d4a3369/recipe/migrations/arch_rebuild.txt#L690 file of [conda-forge-pinning-feedstock](https://github.com/conda-forge/conda-forge-pinning-feedstock), but why isn't auto build start here for linux-aarch64?

**Comment by mfansler** [comment]
The `r-rjags` package depends on the `jags` package, which [has not yet migrated](https://github.com/conda-forge/jags-feedstock/pull/12). The progress of migrations is tracked on the Conda Forge Status page: https://conda-forge.org/status/#aarch64andppc64leaddition.

<img width="319" alt="Screen Shot 2023-09-07 at 3 03 15 PM" src="https://github.com/conda-forge/r-rjags-feedstock/assets/1182216/60006933-d120-42d9-851f-f9bc6df4cc66">
